#!/usr/bin/env ruby
# -*- mode: ruby; coding: utf-8 -*-

require 'csv'
require 'date'
require 'optparse'
require 'pathname'

params = ARGV.getopts('', 'start:0')

account = '資産:流動資産:電子マネー'
accounts = {
  'チャージ' => '資産:流動資産:現金:JPY',
  '運賃支払' => '費用:交通費',
  'バス等運賃支払' => '費用:交通費',
  nil => '不明-JPY'
}
start_no = params['start'].to_i

ARGV.map(&method(:Pathname)).each do |inpath|
  card_name = inpath.basename.to_s.gsub(/_.*/, '')
  open(inpath.sub_ext('.qif'), 'w') do |f|
    f.puts <<-QIF
!Account
N#{account}:#{card_name}
^
!Type:Cash
    QIF

    CSV.read(inpath, headers: true).each do |row|
      no = row['no'].to_i
      date = Date.strptime(row['date'], '%Y/%m/%d')
      info = row['info']
      type = row['type'] =~ /\A(.+)\s/ && $1
      sign = type == 'チャージ' ? +1 : -1
      value = row['value'].to_i * sign

      f.puts <<-QIF if !start_no || no >= start_no
N#{no}
D#{date.strftime('%Y/%m/%d')}
M#{type}
S#{accounts[type] || accounts[nil]}
E#{info}
$#{value}
^
      QIF
    end
  end
end
